#!/usr/bin/env bash
# Install the Swarm Coder agents + skills into your coding harness(es).
# Idempotent and reversible. Run scripts/bootstrap-tools.sh first (for tdd-guard
# + build-hooks, which the builder agent's Claude/AGY hooks reference).
#
#   scripts/install-harness.sh                      # install into all present harnesses
#   scripts/install-harness.sh --harness claude     # just one (claude|codex|agy)
#   scripts/install-harness.sh --uninstall          # remove what this script installs
#
# This repository is the single source. Everything the harnesses see is a symlink
# back into it, so editing a file here takes effect immediately with no re-install:
#   - Claude:      ~/.claude/agents/<agent>.md      -> agents/claude/<agent>.md
#   - Antigravity: ~/.gemini/config/agents/<agent>  -> agents/agy/<agent>/
#   - Codex:       ~/.codex/<agent>.config.toml     -> dist/codex/<agent>.config.toml
#   - Skills:      <harness>/skills/<skill>         -> skills/<skill>
#
# Codex is the one exception to "edit and go": its harness requires a generated
# TOML with the agent body embedded as an escaped string, so it cannot read the
# markdown directly. The generated file is built into dist/ (gitignored) and
# symlinked from ~/.codex, keeping this repo the source — but a change to
# agents/codex/*.md needs a re-run of this script to reach Codex.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HARNESS=all; MODE=install
while (($#)); do case "$1" in
  --harness) HARNESS=${2:?}; shift 2;;
  --install) MODE=install; shift;;
  --uninstall) MODE=uninstall; shift;;
  -h|--help) sed -n '2,24p' "$0"; exit 0;;
  *) echo "unknown arg: $1" >&2; exit 2;;
esac; done

want(){ [[ $HARNESS == all || $HARNESS == "$1" ]]; }
AGENTS=(builder code-reviewer docs research)

# Every directory under skills/ is a skill. Discovered, not listed, so adding
# one is a matter of creating the directory.
mapfile -t SKILLS < <(cd "$ROOT/skills" && find . -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)
((${#SKILLS[@]})) || { echo "no skills found under $ROOT/skills" >&2; exit 1; }

link_skills(){ local d=$1; mkdir -p "$d"
  for s in "${SKILLS[@]}"; do ln -sfn "$ROOT/skills/$s" "$d/$s"; done; }
unlink_skills(){ local d=$1
  for s in "${SKILLS[@]}"; do rm -f "$d/$s"; done; }

# ---- Claude ----
if want claude && [[ -d ~/.claude ]]; then
  if [[ $MODE == install ]]; then
    mkdir -p ~/.claude/agents
    for a in "${AGENTS[@]}"; do ln -sfn "$ROOT/agents/claude/$a.md" ~/.claude/agents/"$a".md; done
    link_skills ~/.claude/skills
    echo "claude: ${#AGENTS[@]} agents + ${#SKILLS[@]} skills linked"
  else
    for a in "${AGENTS[@]}"; do rm -f ~/.claude/agents/"$a".md; done
    unlink_skills ~/.claude/skills
    echo "claude: removed"
  fi
fi

# ---- Codex: skills link directly; agents go through the generated TOML ----
if want codex && [[ -d ~/.codex ]]; then
  if [[ $MODE == install ]]; then
    link_skills ~/.codex/skills
    echo "codex: ${#SKILLS[@]} skills linked"
  else
    unlink_skills ~/.codex/skills
    echo "codex: skills removed"
  fi
fi

# ---- Antigravity ----
if want agy; then
  if [[ $MODE == install ]]; then
    mkdir -p ~/.gemini/config/agents ~/.gemini/config/skills
    for a in "${AGENTS[@]}"; do
      [[ -d $ROOT/agents/agy/$a ]] && ln -sfn "$ROOT/agents/agy/$a" ~/.gemini/config/agents/"$a"
    done
    link_skills ~/.gemini/config/skills
    if [[ -d ~/.agents ]]; then link_skills ~/.agents/skills; fi
    echo "agy: ${#AGENTS[@]} agents + ${#SKILLS[@]} skills linked"
  else
    for a in "${AGENTS[@]}"; do rm -f ~/.gemini/config/agents/"$a"; done
    unlink_skills ~/.gemini/config/skills
    if [[ -d ~/.agents ]]; then unlink_skills ~/.agents/skills; fi
    echo "agy: removed"
  fi
fi

# ---- Codex agent projection: agents/codex/*.md -> dist/codex/*.config.toml -> ~/.codex ----
python3 - "$ROOT" "$MODE" "$HARNESS" <<'PY'
import json, os, re, sys
from pathlib import Path
ROOT, MODE, HARNESS = Path(sys.argv[1]), sys.argv[2], sys.argv[3]
HOME = Path.home()
AGENTS = ["builder", "code-reviewer", "docs", "research"]

if HARNESS in ("all", "codex") and (HOME / ".codex").exists():
    cfg = HOME / ".codex/config.toml"
    text = cfg.read_text() if cfg.exists() else ""
    text = re.sub(
        r"\n*# BEGIN SWARM CODER(?: V3)? AGENTS.*?# END SWARM CODER(?: V3)? AGENTS\n",
        "\n", text, flags=re.DOTALL,
    )
    dist = ROOT / "dist" / "codex"
    if MODE == "install":
        dist.mkdir(parents=True, exist_ok=True)
        for name in AGENTS:
            source = ROOT / "agents" / "codex" / f"{name}.md"
            _, frontmatter, body = source.read_text().split("---", 2)
            fields = {}
            for line in frontmatter.strip().splitlines():
                if ":" in line:
                    key, value = line.split(":", 1)
                    fields[key.strip()] = value.strip().strip("\"'")
            (dist / f"{name}.config.toml").write_text(
                "# Generated by install-harness.sh from agents/codex/%s.md — do not hand-edit.\n" % name
                + f"description = {json.dumps(fields.get('description', ''))}\n"
                + f'model = "{fields.get("model", "gpt-5.6-sol")}"\n'
                + f'model_reasoning_effort = "{fields.get("model_reasoning_effort", "medium")}"\n'
                + f'sandbox_mode = "{fields.get("sandbox_mode", "workspace-write")}"\n'
                + f"developer_instructions = {json.dumps(body.strip())}\n"
            )
            link = HOME / f".codex/{name}.config.toml"
            if link.is_symlink() or link.exists():
                link.unlink()
            os.symlink(dist / f"{name}.config.toml", link)
        block = "# BEGIN SWARM CODER AGENTS\n" + "".join(
            f'[agents.{name}]\nconfig_file = "{HOME}/.codex/{name}.config.toml"\n'
            for name in AGENTS
        ) + "# END SWARM CODER AGENTS\n"
        cfg.write_text((text.rstrip() + "\n\n" + block) if text.strip() else block)
        print(f"codex: {len(AGENTS)} agents generated into dist/codex and linked")
    else:
        for name in AGENTS:
            (HOME / f".codex/{name}.config.toml").unlink(missing_ok=True)
            (dist / f"{name}.config.toml").unlink(missing_ok=True)
        cfg.write_text(text)
        print("codex: agents removed")
PY

if [[ $MODE == install ]]; then
  command -v tdd-guard >/dev/null || echo "note: tdd-guard/build-hooks not found — run scripts/bootstrap-tools.sh --install"
  echo "done."
else
  echo "uninstalled."
fi
