#!/usr/bin/env bash
# Install the Swarm Coder agents + skills into your coding harness(es).
# Idempotent and reversible. Run scripts/bootstrap-tools.sh first (for tdd-guard
# + build-hooks, which the builder agent's Claude/AGY hooks reference).
#
#   scripts/install-harness.sh                      # install into all present harnesses
#   scripts/install-harness.sh --harness claude     # just one (claude|codex|agy)
#   scripts/install-harness.sh --uninstall          # remove what this script installs
#
# Agents are organized by harness under agents/ (agents/claude, agents/codex, agents/agy)
# and deployed directly to their respective directories:
#   - Claude:      ~/.claude/agents/<agent>.md
#   - Codex:       ~/.codex/<agent>.config.toml + [agents.*] in ~/.codex/config.toml
#   - Antigravity: ~/.gemini/config/agents/<agent>/agent.md (+ hooks.json)
#
# Skills are located under skills/ and symlinked into each harness's skills folder.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HARNESS=all; MODE=install
while (($#)); do case "$1" in
  --harness) HARNESS=${2:?}; shift 2;;
  --install) MODE=install; shift;;
  --uninstall) MODE=uninstall; shift;;
  -h|--help) sed -n '2,17p' "$0"; exit 0;;
  *) echo "unknown arg: $1" >&2; exit 2;;
esac; done

want(){ [[ $HARNESS == all || $HARNESS == "$1" ]]; }
SKILLS=(planner research build code-review docs deploy use-other-harness builder-frontend code-reviewer-frontend-review)

link_skills(){ local d=$1; mkdir -p "$d"
  for s in "${SKILLS[@]}"; do ln -sfn "$ROOT/skills/$s" "$d/$s"; done; }
unlink_skills(){ local d=$1
  for s in "${SKILLS[@]}"; do rm -f "$d/$s"; done; }

# ---- Claude: deploy agents + link skills ----
if want claude && [[ -d ~/.claude ]]; then
  if [[ $MODE == install ]]; then
    mkdir -p ~/.claude/agents
    for a in builder code-reviewer docs research; do
      ln -sfn "$ROOT/agents/claude/$a.md" ~/.claude/agents/$a.md
    done
    link_skills ~/.claude/skills
    echo "claude: agents linked + ${#SKILLS[@]} skills linked"
  else
    for a in builder code-reviewer docs research; do
      rm -f ~/.claude/agents/$a.md
    done
    unlink_skills ~/.claude/skills
    echo "claude: removed"
  fi
fi

# ---- Codex: link skills ----
if want codex && [[ -d ~/.codex ]]; then
  if [[ $MODE == install ]]; then
    link_skills ~/.codex/skills
    echo "codex: skills linked"
  else
    unlink_skills ~/.codex/skills
    echo "codex: removed"
  fi
fi

# ---- Antigravity: link skills ----
if want agy; then
  if [[ $MODE == install ]]; then
    mkdir -p ~/.gemini/config/agents ~/.gemini/config/skills
    [[ -d ~/.agents ]] && mkdir -p ~/.agents/skills
    link_skills ~/.gemini/config/skills
    [[ -d ~/.agents ]] && link_skills ~/.agents/skills
    echo "agy: skills linked"
  else
    unlink_skills ~/.gemini/config/skills
    [[ -d ~/.agents ]] && unlink_skills ~/.agents/skills
    echo "agy: removed"
  fi
fi

# ---- Native agent projections (Codex tomls+config and Antigravity agents) ----
python3 - "$ROOT" "$MODE" "$HARNESS" <<'PY'
import json, re, sys
from pathlib import Path
ROOT, MODE, HARNESS = Path(sys.argv[1]), sys.argv[2], sys.argv[3]
HOME = Path.home()
want = lambda h: HARNESS in ("all", h)
AGENTS = ["builder", "code-reviewer", "docs", "research"]

# Codex — parse agents/codex/<name>.md frontmatter + body -> ~/.codex/<name>.config.toml + marked config.toml block
if want("codex") and (HOME/".codex").exists():
    cfg = HOME/".codex/config.toml"; text = cfg.read_text() if cfg.exists() else ""
    text = re.sub(r"\n*# BEGIN SWARM CODER(?: V3)? AGENTS.*?# END SWARM CODER(?: V3)? AGENTS\n", "\n", text, flags=re.DOTALL)
    if MODE == "install":
        for n in AGENTS:
            p = ROOT/"agents"/"codex"/f"{n}.md"
            parts = p.read_text().split("---", 2)
            fm = {}
            for line in parts[1].strip().splitlines():
                if ":" in line:
                    k, v = line.split(":", 1)
                    fm[k.strip()] = v.strip().strip('"\'')
            body = parts[2].strip()
            eff = fm.get("model_reasoning_effort", "medium")
            sb = fm.get("sandbox_mode", "workspace-write")
            model = fm.get("model", "gpt-5.6-sol")
            desc = fm.get("description", "")
            (HOME/f".codex/{n}.config.toml").write_text(
                "# Generated by install-harness.sh; do not hand-edit.\n"
                f"description = {json.dumps(desc)}\n"
                f'model = "{model}"\nmodel_reasoning_effort = "{eff}"\nsandbox_mode = "{sb}"\n'
                f"developer_instructions = {json.dumps(body)}\n")
        block = "# BEGIN SWARM CODER AGENTS\n" + "".join(
            f'[agents.{n}]\nconfig_file = "{HOME}/.codex/{n}.config.toml"\n' for n in AGENTS) + "# END SWARM CODER AGENTS\n"
        cfg.write_text((text.rstrip()+"\n\n"+block) if text.strip() else block)
        print("codex: agents projected")
    else:
        for n in AGENTS: (HOME/f".codex/{n}.config.toml").unlink(missing_ok=True)
        cfg.write_text(text)

# Antigravity — deploy agents/agy/ into ~/.gemini/config/agents/
if want("agy"):
    agents_dir = HOME/".gemini/config/agents"
    if MODE == "install":
        agents_dir.mkdir(parents=True, exist_ok=True)
        for n in AGENTS:
            d = agents_dir/n
            d.mkdir(parents=True, exist_ok=True)
            src_md = ROOT/"agents"/"agy"/n/"agent.md"
            if not src_md.exists():
                src_md = ROOT/"agents"/"agy"/f"{n}.md"
            if src_md.exists():
                (d/"agent.md").write_text(src_md.read_text())
            src_hooks = ROOT/"agents"/"agy"/n/"hooks.json"
            if src_hooks.exists():
                (d/"hooks.json").write_text(src_hooks.read_text())
        print("agy: agents deployed")
    else:
        for n in AGENTS:
            d = agents_dir/n
            (d/"agent.md").unlink(missing_ok=True)
            (d/"hooks.json").unlink(missing_ok=True)
            (agents_dir/f"{n}.md").unlink(missing_ok=True)
            try: d.rmdir()
            except OSError: pass
PY

[[ $MODE == install ]] && { command -v tdd-guard >/dev/null || echo "note: tdd-guard/build-hooks not found — run scripts/bootstrap-tools.sh --install"; echo "done."; } || echo "uninstalled."
