#!/usr/bin/env bash
# Install the Swarm Coder agents + skills into your coding harness(es).
# Idempotent and reversible. Run scripts/bootstrap-tools.sh first (for tdd-guard
# + build-hooks, which the builder agent's Claude hooks reference).
#
#   scripts/install-harness.sh                      # install into all present harnesses
#   scripts/install-harness.sh --harness claude     # just one (claude|codex|agy)
#   scripts/install-harness.sh --uninstall          # remove what this script installs
#
# Read-only leaves (research, code-reviewer) and the docs/build skills are
# symlinked; the Claude builder and every Codex/Antigravity agent are projected
# into that harness's native format. Third-party skills the agents also declare
# (jj, read-the-damn-docs, find-docs, full-output-enforcement, grill-with-docs)
# are installed separately (e.g. `npx skills add ...`), not by this script.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HARNESS=all; MODE=install
while (($#)); do case "$1" in
  --harness) HARNESS=${2:?}; shift 2;;
  --uninstall) MODE=uninstall; shift;;
  -h|--help) sed -n '2,12p' "$0"; exit 0;;
  *) echo "unknown arg: $1" >&2; exit 2;;
esac; done

want(){ [[ $HARNESS == all || $HARNESS == "$1" ]]; }
SKILLS=(planner research build code-review docs deploy use-other-harness)
OWNED=("builder-frontend:agents/builder/skills/frontend"
       "code-reviewer-frontend-review:agents/code-reviewer/skills/frontend-review")

link_skills(){ local d=$1; mkdir -p "$d"
  for s in "${SKILLS[@]}"; do ln -sfn "$ROOT/skills/$s" "$d/$s"; done
  for o in "${OWNED[@]}"; do ln -sfn "$ROOT/${o#*:}" "$d/${o%%:*}"; done; }
unlink_skills(){ local d=$1
  for s in "${SKILLS[@]}"; do rm -f "$d/$s"; done
  for o in "${OWNED[@]}"; do rm -f "$d/${o%%:*}"; done; }

# ---- Claude: symlink read-only agents; project the builder; symlink skills ----
if want claude && [[ -d ~/.claude ]]; then
  if [[ $MODE == install ]]; then
    mkdir -p ~/.claude/agents
    for a in research code-reviewer docs; do ln -sfn "$ROOT/agents/$a/AGENT.md" ~/.claude/agents/$a.md; done
    link_skills ~/.claude/skills
    echo "claude: 3 agent symlinks + builder projection + $(( ${#SKILLS[@]} + ${#OWNED[@]} )) skills"
  else
    for a in research code-reviewer docs builder; do rm -f ~/.claude/agents/$a.md; done
    unlink_skills ~/.claude/skills; echo "claude: removed"
  fi
fi

# ---- Codex skills (symlinks) ----
if want codex && [[ -d ~/.codex ]]; then
  if [[ $MODE == install ]]; then link_skills ~/.codex/skills; echo "codex: skills linked + agents projected"
  else unlink_skills ~/.codex/skills; echo "codex: removed"; fi
fi

# ---- Antigravity skills (symlinks) ----
if want agy && [[ -d ~/.agents ]]; then
  if [[ $MODE == install ]]; then link_skills ~/.agents/skills; echo "agy: skills linked + agents projected"
  else unlink_skills ~/.agents/skills; echo "agy: removed"; fi
fi

# ---- native agent projections (Claude builder real-file, Codex tomls+block, Antigravity agent.md) ----
python3 - "$ROOT" "$MODE" "$HARNESS" <<'PY'
import json, re, sys
from pathlib import Path
ROOT, MODE, HARNESS = Path(sys.argv[1]), sys.argv[2], sys.argv[3]
HOME = Path.home()
# name -> (codex effort, codex sandbox, writer?)
CFG = {"research":("low","read-only",False), "builder":("high","workspace-write",True),
       "docs":("medium","workspace-write",True), "code-reviewer":("medium","read-only",True)}
want = lambda h: HARNESS in ("all", h)
def parts(n):
    p = (ROOT/"agents"/n/"AGENT.md").read_text().split("---", 2)
    fm = {l.split(":",1)[0].strip(): l.split(":",1)[1].strip() for l in p[1].strip().splitlines() if ":" in l}
    return fm, p[2].strip()

# Claude builder — real file carrying the build-hooks TDD gate
if want("claude") and (HOME/".claude/agents").exists():
    dst = HOME/".claude/agents/builder.md"
    if MODE == "install":
        fm, body = parts("builder")
        hooks = {ev:[{**({"matcher":m} if m else {}), "hooks":[{"type":"command","command":f"/home/anvil/.local/bin/build-hooks claude {ev}"}]}]
                 for ev,m in [("PreToolUse","Edit|Write|MultiEdit|NotebookEdit"),("PostToolUse","Bash"),("Stop",""),("SubagentStop","")]}
        dst.write_text(f"---\nname: builder\ndescription: {fm['description']}\ntools: {fm['tools']}\nhooks: {json.dumps(hooks)}\n---\n\n{body}\n")
    elif dst.exists(): dst.unlink()

# Codex — one .config.toml per agent + a marked [agents.*] block in config.toml
if want("codex") and (HOME/".codex").exists():
    cfg = HOME/".codex/config.toml"; text = cfg.read_text() if cfg.exists() else ""
    text = re.sub(r"\n*# BEGIN SWARM CODER(?: V3)? AGENTS.*?# END SWARM CODER(?: V3)? AGENTS\n", "\n", text, flags=re.DOTALL)
    if MODE == "install":
        for n,(eff,sb,_) in CFG.items():
            _, body = parts(n)
            (HOME/f".codex/{n}.config.toml").write_text(
                "# Generated by install-harness.sh; do not hand-edit.\n"
                f'model = "gpt-5.6-sol"\nmodel_reasoning_effort = "{eff}"\nsandbox_mode = "{sb}"\n'
                f"developer_instructions = {json.dumps(body)}\n")
        block = "# BEGIN SWARM CODER AGENTS\n" + "".join(
            f'[agents.{n}]\nconfig_file = "{HOME}/.codex/{n}.config.toml"\n' for n in CFG) + "# END SWARM CODER AGENTS\n"
        cfg.write_text((text.rstrip()+"\n\n"+block) if text.strip() else block)
    else:
        for n in CFG: (HOME/f".codex/{n}.config.toml").unlink(missing_ok=True)
        cfg.write_text(text)

# Antigravity — agent.md per agent
if want("agy") and (HOME/".gemini/config/agents").exists():
    for n,(eff,sb,w) in CFG.items():
        d = HOME/f".gemini/config/agents/{n}"
        if MODE == "install":
            fm, body = parts(n)
            tools = ["view_file","grep_search","run_command"] + (["replace_file_content"] if w else [])
            d.mkdir(parents=True, exist_ok=True)
            (d/"agent.md").write_text("---\n"f"name: {n}\n"f'description: "{fm["description"]}"\n'"tools:\n"
                + "".join(f"  - {t}\n" for t in tools)
                + 'mainAgent: true\nsubagent: true\nmodel: "gemini-3.7-flash-high"\ncommandExecutionPolicy: sandbox\n---\n\n'+body+"\n")
        else:
            (d/"agent.md").unlink(missing_ok=True)
            try: d.rmdir()
            except OSError: pass
print("agent projections", MODE + "ed")
PY

[[ $MODE == install ]] && { command -v tdd-guard >/dev/null || echo "note: tdd-guard/build-hooks not found — run scripts/bootstrap-tools.sh --install"; echo "done."; } || echo "uninstalled."
